/**
 * Turning a résumé file into text.
 *
 * Your PDF stays the single source of truth — the same file you upload to an
 * application is the one jobscout reads. The extracted text is generated,
 * regenerated whenever the file changes, and never edited by hand.
 */

import { readFile, stat } from "node:fs/promises";
import { extname } from "node:path";

export type ResumeFormat = "pdf" | "docx" | "text";

export interface ExtractedResume {
  text: string;
  format: ResumeFormat;
  words: number;
  /** True when the file yielded almost nothing — usually a scanned image. */
  suspect: boolean;
}

export class ResumeError extends Error {
  constructor(
    message: string,
    readonly hint?: string,
  ) {
    super(message);
    this.name = "ResumeError";
  }
}

/** A résumé shorter than this is almost certainly an extraction failure. */
const MIN_WORDS = 60;

function formatOf(path: string): ResumeFormat {
  switch (extname(path).toLowerCase()) {
    case ".pdf":
      return "pdf";
    case ".docx":
      return "docx";
    case ".txt":
    case ".md":
      return "text";
    default:
      throw new ResumeError(
        `Unsupported résumé format: ${extname(path) || "(none)"}`,
        "Use .pdf, .docx, .txt, or .md.",
      );
  }
}

async function extractPdf(path: string): Promise<string> {
  // Imported lazily: pdf.js is large, and no other command needs it.
  const { extractText, getDocumentProxy } = await import("unpdf");
  const bytes = new Uint8Array(await readFile(path));
  const doc = await getDocumentProxy(bytes);
  const { text } = await extractText(doc, { mergePages: true });
  return Array.isArray(text) ? text.join("\n") : text;
}

async function extractDocx(path: string): Promise<string> {
  const mammoth = await import("mammoth");
  const result = await mammoth.extractRawText({ path });
  return result.value;
}

/**
 * Tidy extracted text without changing its content.
 *
 * PDF extraction routinely splits words across layout boxes — the résumé this
 * was built against produced "MEGA V ARUN N" and "FinT ech". Those are real
 * artefacts, but repairing them means guessing, so the text is only normalised
 * for whitespace and left otherwise exactly as extracted.
 */
function tidy(raw: string): string {
  return raw
    .replace(/\r\n?/g, "\n")
    .replace(/[ \t]+/g, " ")
    .replace(/ *\n */g, "\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export async function extractResume(path: string): Promise<ExtractedResume> {
  try {
    const info = await stat(path);
    if (!info.isFile()) throw new ResumeError(`${path} is not a file`);
  } catch (err) {
    if (err instanceof ResumeError) throw err;
    throw new ResumeError(`Résumé not found: ${path}`, "Re-run `jobscout init` to point at it.");
  }

  const format = formatOf(path);
  let raw: string;

  try {
    raw =
      format === "pdf"
        ? await extractPdf(path)
        : format === "docx"
          ? await extractDocx(path)
          : await readFile(path, "utf8");
  } catch (err) {
    throw new ResumeError(
      `Could not read ${format.toUpperCase()}: ${err instanceof Error ? err.message : String(err)}`,
      format === "pdf" ? "If it is a scanned image, export a text-based PDF instead." : undefined,
    );
  }

  const text = tidy(raw);
  const words = text.split(/\s+/).filter(Boolean).length;

  if (words === 0) {
    throw new ResumeError(
      "Extracted no text at all.",
      "The file is probably a scanned image. Export a text-based PDF, or supply a .txt.",
    );
  }

  return { text, format, words, suspect: words < MIN_WORDS };
}

/** The generated file's header, so nobody mistakes it for something to edit. */
export function resumeHeader(sourceName: string): string {
  return [
    `<!-- Generated by jobscout from ${sourceName}. Do not edit by hand —`,
    "     it is rebuilt whenever the résumé changes. -->",
    "",
  ].join("\n");
}
